[build]
builder = "nixpacks"

[deploy]
startCommand = "/app/.venv/bin/python -m celery -A app.tasks.celery_app worker --loglevel=info --pool=solo"

[phases.setup]
nixPkgs = ["python311", "ffmpeg"]

[phases.install]
cmds = [
  "curl -LsSf https://astral.sh/uv/install.sh | sh",
  "/root/.local/bin/uv venv /app/.venv",
  "/root/.local/bin/uv pip install -r requirements.txt --python /app/.venv/bin/python"
]
